# Generated by Django 4.2.29 on 2026-03-19 09:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import kontingent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medlemmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=kontingent.models.current_year)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8)),
                ('due_date', models.DateField(default=kontingent.models.default_due_date)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('exempt', 'Exempt')], default='pending', max_length=20)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_fees', to='medlemmer.member')),
            ],
            options={
                'ordering': ['-year', 'member__user__username'],
                'unique_together': {('member', 'year')},
            },
        ),
    ]
